In [3]:
import numpy as np

X = np.array([
    [1, 2, 3], 
    [1, 2, 5], 
    [1, 3, 4], 
    [1, 5, 9]
])

y = np.array([
    [1],
    [5],
    [6],
    [8]
])

In [7]:
#step1
XtX = np.dot(X.T, X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [12]:
#Step2
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [18]:
#Step3
Xty = np.dot(X.T, y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [20]:
#Step4
w  = np.dot(XtX_inv, Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learnで実装

In [21]:
import sklearn

In [22]:
#重回帰分析のみ読み込み
from sklearn.linear_model import LinearRegression

In [23]:
#モデルの宣言
model = LinearRegression()

In [24]:
#モデルの学習 <- パラメータの調整
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [27]:
#調整後のパラメータ
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [29]:
model.intercept_

array([-0.14285714])

In [30]:
#予測精度 <- 決定係数
model.score(X, y)

0.6923076923076926

In [31]:
#予測値の計算
x = np.array([[1, 2, 3]])

In [34]:
y_pred = model.predict(x)
y_pred

array([[3.]])